# Generated by Django 4.2.8 on 2024-02-22 09:21

import api_v1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='corpus',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя в Telegram'),
        ),
        migrations.AlterField(
            model_name='request',
            name='apartment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api_v1.models.get_request_photo_path, verbose_name='Фото обращения'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя в Telegram'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время конца работы'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала работы'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('street', 'number', 'corpus')},
        ),
    ]
