# Generated by Django 4.2.8 on 2024-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentBotToken', models.TextField(verbose_name='Токен бота жителей')),
                ('staffBotToken', models.TextField(verbose_name='Токен бота мастеров')),
            ],
            options={
                'verbose_name': 'Токены ботов',
                'verbose_name_plural': 'Токены ботов',
            },
        ),
    ]
