# Generated by Django 4.2.8 on 2024-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingcomplex',
            name='street',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
    ]
